---
- hosts: archiva
  gather_facts: no
  user: root
  vars:
    archiva_ver: 1.4-M4
    archiva_url: http://mirror.cogentco.com/pub/apache/archiva/{{archiva_ver}}/binaries/apache-archiva-{{archiva_ver}}-bin.zip

  tasks:
  - name: Install deps and niceties
    yum: name=$item state=latest
    with_items:
     - wget
     - java-1.7.0-openjdk
     - screen
     - vim-enhanced
     - unzip
     - libselinux-python
  - name: Create the archiva directory
    file: path=/opt/archiva state=directory
  - name: Download archiva 
    get_url: dest=/opt/archiva/apache-archiva-{{archiva_ver}}-bin.zip url={{archiva_url}}
  - name: Explode archiva
    action: command creates=/opt/archiva/apache-archiva-{{archiva_ver}} chdir=/opt/archiva unzip /opt/archiva/apache-archiva-{{archiva_ver}}-bin.zip 
  - name: Link the init script
    action: file src=/opt/archiva/apache-archiva-{{archiva_ver}}/bin/archiva dest=/etc/init.d/archiva   owner=root group=root state=link  
  - name: Add the service
    action: command /sbin/chkconfig --add archiva
  - name: Start service and ensure is running on reboot
    action: service name=archiva state=started enabled=yes
  
  - name: Open the correct IPTables ports
    lineinfile: dest=/etc/sysconfig/iptables
                  regexp="^-A INPUT -p {{item.protocol}} -m {{item.protocol}} --dport {{item.port}} -j ACCEPT$"
                  line="-A INPUT -p {{item.protocol}} -m {{item.protocol}} --dport {{item.port}} -j ACCEPT"
                  insertafter="^:OUTPUT ACCEPT \[\d*:\d*\]$"
    with_items:
     - { protocol: tcp, port: 8080 }
     - { protocol: tcp, port: 22 }
    notify:
     - restart iptables

  handlers:
     - name: restart iptables
       action: service name=iptables state=restarted

